development:
  sessions:
    default:
      hosts:
        - localhost
      database: jukebox_dev

test:
  sessions:
    default:
      hosts:
        - localhost
      database: jukebox_test

production:
  sessions:
    default:
      uri: "<%=ENV['PROD_MONGODB']%>"
